// ABOUTME: Automated setup command for first-time configuration
// ABOUTME: Guides users through runtime detection and config generation

package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/harper/acp-relay/internal/runtime"
	"github.com/harper/acp-relay/internal/xdg"
)

func runSetup() {
	fmt.Println("🚀 ACP-Relay Automated Setup")
	fmt.Println()

	// Detect container runtime
	fmt.Println("🔍 Detecting container runtime...")
	best := runtime.DetectBest()

	if best == nil {
		fmt.Println("❌ No container runtime detected (Docker, Podman, or Colima)")
		fmt.Println("   Install Docker: https://docs.docker.com/get-docker/")
		fmt.Println("   Or install Colima: brew install colima && colima start")
		os.Exit(1)
	}

	fmt.Printf("✅ Found: %s at %s\n", best.Name, best.SocketPath)
	fmt.Println("   (Auto-selected. To use a different runtime, edit config.yaml after setup)")
	fmt.Println()

	// Get config directory
	configDir := filepath.Join(xdg.ConfigHome(), "acp-relay")
	configPath := filepath.Join(configDir, "config.yaml")

	// Check if config already exists
	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("⚠️  Config already exists at: %s\n", configPath)
		fmt.Println("   Delete it first if you want to regenerate.")
		os.Exit(1)
	}

	// Create config directory
	if err := os.MkdirAll(configDir, 0755); err != nil {
		fmt.Printf("❌ Failed to create config directory: %v\n", err)
		os.Exit(1)
	}

	// Generate config
	dataDir := filepath.Join(xdg.DataHome(), "acp-relay")
	configContent := fmt.Sprintf(`# ACP-Relay Configuration
# Generated by setup command

server:
  http_port: 8080
  http_host: "0.0.0.0"
  websocket_port: 8081
  websocket_host: "0.0.0.0"
  management_port: 8082
  management_host: "127.0.0.1"  # localhost only for security

agent:
  mode: "container"  # container mode (command field not used)

  env:
    ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"

  startup_timeout_seconds: 10
  max_concurrent_sessions: 100

  container:
    image: "acp-relay-agent:latest"
    docker_host: "unix://%s"
    network_mode: "bridge"
    memory_limit: "512m"
    cpu_limit: 1.0
    workspace_host_base: "%s/workspaces"
    workspace_container_path: "/workspace"
    auto_remove: true
    startup_timeout_seconds: 10

database:
  path: "%s/relay-messages.db"
`, best.SocketPath, dataDir, dataDir)

	// Write config file
	if err := os.WriteFile(configPath, []byte(configContent), 0644); err != nil {
		fmt.Printf("❌ Failed to write config: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ Config generated at: %s\n", configPath)
	fmt.Println()
	fmt.Println("📝 Next steps:")
	fmt.Println("   1. Set ANTHROPIC_API_KEY environment variable")
	fmt.Println("   2. Build Docker image: docker build -t acp-relay-agent:latest .")
	fmt.Println("   3. Start server: acp-relay serve --config", configPath)
	fmt.Println()
	fmt.Println("🎉 Setup complete!")
}
